<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Modul_5_Embeddings</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OllamaSharp" Version="5.4.30" />
    </ItemGroup>

    <ItemGroup>
      <None Update="corpus.txt" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
