<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Modul_1_PromptEngineering</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.47.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="prompts\*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
